<?php

namespace Database\Seeders;

use App\Models\Module;
use Illuminate\Database\Seeder;

class KbPagesSeeder extends Seeder
{
    public function run(): void
    {
        $pages = [
            // ─── Methodology ────────────────────────────────────────────────────
            [
                'id' => 'backend-learning-program',
                'slug' => 'Backend_Learning_Program',
                'file' => 'kb.Backend_Learning_Program',
                'title' => 'Программа & Расписание',
                'description' => 'Roadmap 9 фаз, 16-недельное расписание с интервальным повторением, 24 вопроса собеседования, топ курсы и ресурсы.',
                'badge' => 'ROADMAP',
                'badge_class' => 'badge-program',
                'icon' => 'map',
                'icon_class' => 'ic-purple',
                'group_name' => 'Modules',
                'layout' => 'sidebar',
                'sort_order' => 0,
            ],

            // ─── Core Modules KB_1 - KB_8 ───────────────────────────────────────
            [
                'id' => 'kb1',
                'slug' => 'KB_1_PHP_Core',
                'file' => 'kb.KB_1_PHP_Core',
                'title' => 'PHP Core',
                'description' => 'Типы, ООП, traits, интерфейсы, магические методы, namespaces, PHP 8.x, генераторы, closures. 12 разделов.',
                'badge' => 'PHP',
                'badge_class' => 'badge-php',
                'icon' => 'code-2',
                'icon_class' => 'ic-purple',
                'group_name' => 'Modules',
                'layout' => 'sidebar',
                'sort_order' => 10,
            ],
            [
                'id' => 'kb2',
                'slug' => 'KB_2_SQL_Database',
                'file' => 'kb.KB_2_SQL_Database',
                'title' => 'SQL & Базы данных',
                'description' => 'Реляционная модель, нормализация, JOIN-семантика, индексы (B-Tree, GIN, covering, leftmost), EXPLAIN, N+1, ACID, MVCC, deadlock, window-функции и CTE, MySQL vs Postgres, PDO. Middle/senior.',
                'badge' => 'SQL',
                'badge_class' => 'badge-sql',
                'icon' => 'database',
                'icon_class' => 'ic-teal',
                'group_name' => 'Modules',
                'layout' => 'sidebar',
                'sort_order' => 20,
            ],
            [
                'id' => 'kb3',
                'slug' => 'KB_3_Laravel',
                'file' => 'kb.KB_3_Laravel',
                'title' => 'Laravel',
                'description' => 'Request Lifecycle, Routing с scoped bindings, Middleware и terminate, Validation/FormRequest, Eloquent основа, Cache с lock, Queues (retry, idempotency, afterCommit), Events, Scheduler, Auth/Gates/Policies, Octane long-running. Middle/senior.',
                'badge' => 'LARAVEL',
                'badge_class' => 'badge-laravel',
                'icon' => 'flame',
                'icon_class' => 'ic-orange',
                'group_name' => 'Modules',
                'layout' => 'sidebar',
                'sort_order' => 30,
            ],
            [
                'id' => 'kb4',
                'slug' => 'KB_4_Security',
                'file' => 'kb.KB_4_Security',
                'title' => 'Безопасность',
                'description' => 'OWASP Top 10, пароли (bcrypt/argon2), JWT/Sanctum, OAuth 2.0 + PKCE, RBAC/ABAC, CSRF, XSS (3 типа), SQL Injection, CORS, Rate Limiting, TLS, Security Headers, Secrets Management. Middle/senior.',
                'badge' => 'SECURITY',
                'badge_class' => 'badge-security',
                'icon' => 'shield-check',
                'icon_class' => 'ic-danger',
                'group_name' => 'Дополнительно',
                'layout' => 'sidebar',
                'sort_order' => 40,
            ],
            [
                'id' => 'kb5',
                'slug' => 'KB_5_Architecture',
                'file' => 'kb.KB_5_Architecture',
                'title' => 'Архитектура & Паттерны',
                'description' => 'SOLID принципы, GoF-паттерны (Factory, Strategy, Observer, Decorator, Adapter), Repository vs Active Record, Service Layer, DTO, DDD-тактика (Entity, Value Object, Aggregate), Clean Architecture, Hexagonal. Middle/senior.',
                'badge' => 'PATTERNS',
                'badge_class' => 'badge-arch',
                'icon' => 'layers',
                'icon_class' => 'ic-warning',
                'group_name' => 'Дополнительно',
                'layout' => 'sidebar',
                'sort_order' => 50,
            ],
            [
                'id' => 'kb6',
                'slug' => 'KB_6_Testing_DevOps',
                'file' => 'kb.KB_6_Testing_DevOps',
                'title' => 'Тестирование & DevOps',
                'description' => 'PHPUnit/Pest основы, unit/feature тесты, TDD, Docker и Docker Compose, Git workflow, CI/CD (GitHub Actions), Nginx конфиг, Deploy стратегии (zero-downtime). Дополняет KB_14 по тестированию.',
                'badge' => 'DEVOPS',
                'badge_class' => 'badge-devops',
                'icon' => 'flask-conical',
                'icon_class' => 'ic-blue',
                'group_name' => 'Дополнительно',
                'layout' => 'sidebar',
                'sort_order' => 60,
            ],
            // ─── Advanced KB_9+ ─────────────────────────────────────────────────
            [
                'id' => 'kb9',
                'slug' => 'KB_9_Laravel_Inheritance',
                'file' => 'kb.KB_9_Laravel_Inheritance',
                'title' => 'Наследование & Базовые классы',
                'description' => 'Что наследуют Controller, Model, FormRequest, Middleware, Job, Command, Notification, Mailable, Event/Listener. Интерфейсы, трейты, фасады — цепочки наследования и API родителей.',
                'badge' => 'INHERITANCE',
                'badge_class' => 'badge-laravel',
                'icon' => 'git-branch',
                'icon_class' => 'ic-purple',
                'group_name' => 'Дополнительно',
                'layout' => 'sidebar',
                'sort_order' => 90,
            ],
            [
                'id' => 'kb10',
                'slug' => 'KB_10_Laravel_Helpers',
                'file' => 'kb.KB_10_Laravel_Helpers',
                'title' => 'Хелперы & методы',
                'description' => 'Практический справочник: request/validation, Eloquent, Collections, Str, Arr, Carbon, session/auth, routing, debug, artisan. Каждый хелпер с объяснением и use case. 95% повседневных задач.',
                'badge' => 'HELPERS',
                'badge_class' => 'badge-laravel',
                'icon' => 'wrench',
                'icon_class' => 'ic-blue',
                'group_name' => 'Modules',
                'layout' => 'sidebar',
                'sort_order' => 100,
            ],
            [
                'id' => 'kb11',
                'slug' => 'KB_11_Cloud_DevOps_Networking',
                'file' => 'kb.KB_11_Cloud_DevOps_Networking',
                'title' => 'Cloud & DevOps — Сети',
                'description' => 'Виртуализация (VM, гипервизоры), типы сетей, OSI и TCP/IP с примерами, MAC/IPv4/IPv6, ARP/TCP/UDP/ICMP/порты, подсети и CIDR, NAT, VLAN. С аналогиями и диаграммами — понятно.',
                'badge' => 'NETWORKING',
                'badge_class' => 'badge-devops',
                'icon' => 'network',
                'icon_class' => 'ic-teal',
                'group_name' => 'Modules',
                'layout' => 'sidebar',
                'sort_order' => 110,
            ],
            [
                'id' => 'kb12',
                'slug' => 'KB_12_Eloquent_Advanced',
                'file' => 'kb.KB_12_Eloquent_Advanced',
                'title' => 'Eloquent Advanced',
                'description' => 'Глубокий разбор: все relations (включая polymorphic, hasManyThrough), кастомные касты, observers, race conditions, chunk vs cursor vs lazy. С практикой и interview-вопросами middle/senior уровня.',
                'badge' => 'ELOQUENT',
                'badge_class' => 'badge-laravel',
                'icon' => 'database',
                'icon_class' => 'ic-orange',
                'group_name' => 'Advanced',
                'layout' => 'sidebar',
                'sort_order' => 120,
            ],
            [
                'id' => 'kb13',
                'slug' => 'KB_13_Service_Container_DI',
                'file' => 'kb.KB_13_Service_Container_DI',
                'title' => 'Service Container & DI',
                'description' => 'Архитектурное ядро Laravel: bindings, contextual, tagged, autowiring, Service Providers, deferred, package providers. Practical patterns для расширяемых модулей и тестов.',
                'badge' => 'CONTAINER',
                'badge_class' => 'badge-arch',
                'icon' => 'box',
                'icon_class' => 'ic-purple',
                'group_name' => 'Advanced',
                'layout' => 'sidebar',
                'sort_order' => 130,
            ],
            [
                'id' => 'kb14',
                'slug' => 'KB_14_Testing_Deep',
                'file' => 'kb.KB_14_Testing_Deep',
                'title' => 'Тестирование — глубоко',
                'description' => 'Test doubles по Мезаросу, дизайн тестов, пирамида/трофей/соты, DB-стратегии, параллельные тесты, время и очереди, mutation testing, coverage, snapshot, миграция legacy. Дополняет KB_6.',
                'badge' => 'TESTING',
                'badge_class' => 'badge-devops',
                'icon' => 'flask-conical',
                'icon_class' => 'ic-blue',
                'group_name' => 'Advanced',
                'layout' => 'sidebar',
                'sort_order' => 140,
            ],
            [
                'id' => 'kb16',
                'slug' => 'KB_16_JavaScript_jQuery',
                'file' => 'kb.KB_16_JavaScript_jQuery',
                'title' => 'JavaScript + jQuery — база',
                'description' => 'База JS (типы, var/let/const, ==/===, функции + arrow this, массивы map/filter/reduce, DOM, events, Promise, async/await, fetch) + jQuery (селекторы, DOM, events + delegated, $.ajax, CSRF в Laravel).',
                'badge' => 'FRONTEND',
                'badge_class' => 'badge-warning',
                'icon' => 'code',
                'icon_class' => 'ic-orange',
                'group_name' => 'Modules',
                'layout' => 'sidebar',
                'sort_order' => 150,
            ],
            [
                'id' => 'kb17',
                'slug' => 'KB_17_Vue',
                'file' => 'kb.KB_17_Vue',
                'title' => 'Vue.js — база',
                'description' => 'Vue 3: Options + Composition API, реактивность (ref/reactive/computed/watch), директивы, компоненты, composables, Vue Router, Pinia, HTTP (axios), под капотом (Proxy + Virtual DOM), интеграция с Laravel (Blade, CSRF, полный поток).',
                'badge' => 'FRONTEND',
                'badge_class' => 'badge-warning',
                'icon' => 'component',
                'icon_class' => 'ic-orange',
                'group_name' => 'Modules',
                'layout' => 'sidebar',
                'sort_order' => 160,
            ],

            // ─── Methodology ────────────────────────────────────────────────────
            [
                'id' => 'schedule-daily',
                'slug' => 'Schedule_Daily',
                'file' => 'kb.Schedule_Daily',
                'title' => 'Дневное расписание',
                'description' => 'Детальный план занятий на день с интервальным повторением.',
                'badge' => 'SCHEDULE',
                'badge_class' => 'badge-program',
                'icon' => 'calendar',
                'icon_class' => 'ic-purple',
                'group_name' => 'Methodology',
                'layout' => 'fullwidth',
                'sort_order' => 200,
            ],
        ];

        foreach ($pages as $page) {
            Module::updateOrCreate(['id' => $page['id']], $page);
        }
    }
}
